apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-2-server.fullname" . }}
  labels:
    {{- include "service-2-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalName: {{ include "service-2-server.fullname" . }}.default.svc.cluster.local
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "service-2-server.selectorLabels" . | nindent 4 }}
